### ISSUE TITLE
ToDo for v0.3.3

### ISSUE THREAD

**Issue by SeBassTian23** [Photosynq/PhotosynQ-ChromeApp#66]
**Minor things to do before the next release and testing**
- [x] Fix position of toastr messages
- [x] Put in missing links to the documentation
- [x] Check equations for transformations and smoothing 
- [x] Test the new discussion features
- [x] Test GCM behavior
- [x] GCM Messages need to expire after a few minutes - no need, since they are collapsable
- [x] Projects don't get deleted on other devices
- [x] Remove not fully supported devices from list - we keep them
- [x] Copy result table doesn't work
